---
title: "R Notebook"
output: html_notebook
---
JPdataOSK <- read.csv("JPdata.csv")

library(maptools)
library(RColorBrewer)
library(classInt)
library(OpenStreetMap)
library(sp)
library(rgeos)
library(tmap)
library(tmaptools)
library(sf)
library(rgdal)
library(geojsonio)

JPdataSF<- read_shape("C:\\Users\\demi8\\OneDrive\\桌面\\Postgrad\\CASA0005 GIS\\Assignment1\\JPN_adm\\JPN_adm1.shp", as.sf = TRUE)

qtm(JPdataSF)

library(ggplot2)

#rename the column to ensure it can be found for matching
JPdataOSK<- edit(JPdataOSK)

#Join attribute data
JPdataMap <- append_data(JPdataSF,JPdataOSK, key.shp = "ID_1", key.data
= "ID_prefecture", ignore.duplicates = TRUE)

#Making maps
library(tmap)
library(tmaptools)
tmap_mode("plot")
qtm(JPdataMap, fill = "Monthly_rent__yen_2008")



library(shinyjs)
tmaptools::palette_explorer()

#Adding basemaps by downloading from Open Street Map
JPdata_osm <- read_osm(JPdataMap, type = "esri", zoom = NULL)

qtm(JPdata_osm) +
tm_shape(JPdataMap) +
tm_polygons("Monthly_rent__yen_2008",
style="kmeans",                                                             
palette="PuRd", n = 5,
midpoint=NA,
title="Rent monthly in each prefecture",
alpha = 0.5) +
tm_compass(position = c("left", "bottom"),type = "arrow") +
tm_scale_bar(position = c("left", "bottom")) +
tm_layout(title = "Average Monthly rent for a living house",legend.position = c("right", "bottom"))

